In [1]:
import numpy as np

In [19]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(arr)

print(arr[1,2,1],arr.shape)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
17 (2, 3, 3)


In [28]:
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

print(arr1**2)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[100 121 144]
  [169 196 225]
  [256 289 324]]]


In [30]:
arr2=np.array([1,2,3,4,5])
arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2+arr3)

[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [32]:
arr4=np.array([[1,2,3],[4,5,6],[7,8,9]])
mean=np.mean(arr4)
std_dev=np.std(arr4)
norm_arr=(mean/std_dev)
print(norm_arr)

1.9364916731037085


In [33]:
arr5=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr5))
print(np.prod(arr5))
print(np.min(arr5))
print(np.max(arr5))
print(np.mean(arr5))
print(np.std(arr5))
print(np.var(arr5))

45
362880
1
9
5.0
2.581988897471611
6.666666666666667
