In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape,type(arr2D))

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) <class 'numpy.ndarray'>


In [3]:
arr1=np.zeros((2,3),dtype="int64")
print(arr1)

arr2=np.ones((3,3))
print(arr2)

arr3=np.full((2,3),13)
print(arr3,type(arr3))

arr4=np.eye(3,dtype="int64")
print(arr4,arr4.shape)

arr5=np.arange(0,10)
print(arr5)

arr6=np.linspace(1,100,3)
print(arr6)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[13 13 13]
 [13 13 13]] <class 'numpy.ndarray'>
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[0 1 2 3 4 5 6 7 8 9]
[  1.   50.5 100. ]


In [4]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [12]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped)

flattened=arr.flatten()
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6] (6,)


In [13]:
arr=np.array([1,2,3,4,5])
print(arr[2])

arr1=np.array([[1,2,3],[4,5,6]])
print(arr1[0][1])

arr2=np.array([1,2,3,4,5])
idx=[0,2,4]
print(arr2[idx])

arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3[arr3%2==0])

3
2
[1 3 5]
[2 4 6 8]


In [14]:
arr=np.array([1,2,3,4,5,6])
print(arr[1:4])

[2 3 4]


In [15]:
arr=np.array([1,2,3,4,5,6])
sub_arr=arr[1:3].copy()
sub_arr[0]=200
print(sub_arr)
print(arr)

[200   3]
[1 2 3 4 5 6]


In [16]:
arr1=np.array([1+2j])
arr2=np.array([4+3j])
print(arr1+arr2)

[5.+5.j]


In [17]:
import time

In [18]:
b=10000000
start=time.time()
c=np.arange(b)**2
end=time.time()
print(end-start)


0.09403061866760254
