In [1]:
import torch

In [2]:
print(torch.__version__)

2.13.0+cpu


In [3]:
import torch.nn as nn 

In [4]:
torch.manual_seed(42)

In [5]:
inputs=torch.tensor([1.0,2.0,3.0])
neuron=nn.Linear(in_features=3,out_features=1)
output=neuron(inputs)

In [6]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [7]:
neuron.weight@inputs+neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [8]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [9]:
import pandas as pd

In [10]:
from sklearn.model_selection import train_test_split